name: John Nunemaker
author: John Nunemaker
markdown: redcarpet
pygments: true
exclude: ["script", "Gemfile", "Gemfile.lock"]
permalink: /:title/
timezone: America/Indiana/Indianapolis
title: John Nunemaker
tagline: Addicted to Stable
