name: John Nunemaker
author: John Nunemaker
markdown: redcarpet
pygments: true
exclude: ["script", "Gemfile", "Gemfile.lock"]
permalink: /:title/
timezone: America/Indiana/Indianapolis

title: John Nunemaker
tagline: 'addicted to stable'
description: 'The Programmer Formerly Known as Addicted To New.'
