#!/usr/bin/env ruby
#/ Usage: new
#/
#/ Create a new post.
#/
#/ Examples:
#/
#/   new
#/
require "yaml"

def ask(message)
  print message
  STDIN.gets.chomp
end

title = ask("# ")
file_name = title.gsub(/[^\w]/, '-').squeeze('-')
article = YAML.dump({"title" => title, "layout" => "post"})
article << "---\n\n"
path = "_posts/#{Time.now.strftime("%Y-%m-%d")}#{'-' + file_name}.md"
unless File.exist?(path)
	File.open(path, "w") do |file|
		file.write article
	end
  puts "A new article was created at #{path}."
else
  puts "There was an error creating the article, #{path} already exists."
end
exit
