#!/bin/sh
# Run this thing.
#
# Usage:
#   server
#   open http://localhost:4000

set -e
cd $(dirname "$0")/..

script/bootstrap && bin/jekyll serve --watch --drafts --incremental --port 5000
exit=$?
exit $exit
